### ISSUE TITLE
Examine Laws on Road Use

### ISSUE THREAD

**Issue by charicner** [charicner/Make-Cadets-March#5]
Examine Texas Laws on Pedestrian Road Use
To ensure that the chosen routes comply with Texas state regulations, we will examine relevant sections of the Texas Transportation Code, mainly focusing on Title 7 Chapter 552, which covers pedestrian rights and restrictions on highways and Farm-to-Market roads. We will also confirm any group size limits for pedestrians to ensure compliance during the hike.
This information will be crucial in determining route eligibility and help finalize a legally viable route for the hike.

**Comment by Agu303** [comment]
- Completed research, just need to create task 3 graphic and display info onto our poster
